### ISSUE TITLE
 it gets clicked even when it's still not visible.

### ISSUE THREAD

**Issue by microcian** [tiancaiCC/SpringFloatingActionMenu#10]
I Pressed Cancel Button and and view is disappear but still Clickable , have you solution of this ?

**Comment by brucetoo** [comment]
Just check out the PR  https://github.com/tiancaiCC/SpringFloatingActionMenu/pull/11

**Comment by lusccc** [comment]
Fixed by @brucetoo. Thanks~ 好人一生平安
