### ISSUE TITLE
Disable move Fab

### ISSUE THREAD

**Issue by pishguy** [tiancaiCC/SpringFloatingActionMenu#13]
how can i disable moving fab on page? i want to fixed on screen and user don't moving  and playing with that

**Comment by pishguy** [comment]
no any body to help me? how to disable that?

**Comment by amanzan** [comment]
You could just comment the method that moves the FAB: applyFollowAnimation()

**Comment by lusccc** [comment]
I have added this feature. Thanks~

**Comment by pishguy** [comment]
​Thanks man :)
