### ISSUE TITLE
below layouts are clicable when spring menu is visible

### ISSUE THREAD

**Issue by pishguy** [tiancaiCC/SpringFloatingActionMenu#16]
Hi man, thanks to resolve some bugs, please see this screen video. after opening menu, below layouts are clickable

http://s6.picofile.com/file/8257447550/video_2016_06_26_08_08_25.mov.html

**Comment by amanzan** [comment]
Yeah I've seen this issue too. I guess setting the layout that holds the buttons as clickable would fix the problem

**Comment by pishguy** [comment]
@amanzan you mean is i must be disable clickable widgets on layouts?

**Comment by amanzan** [comment]
@tux-world I mean, the dark blue view that has the buttons when the menu is open, needs to be clickable. I just tested with the sample app and it works. If you open SpringFloatingActionMenu.java and add "view.setClickable(true);" in line 355, problem is fixed

**Comment by pishguy** [comment]
@amanzan yes, your right, Thanks man :+1:

**Comment by lusccc** [comment]
Fixed by @amanzan, thanks~
