### ISSUE TITLE
Did the Follow-Circles animation just disappeared?

### ISSUE THREAD

**Issue by amanzan** [tiancaiCC/SpringFloatingActionMenu#19]
Apparently that cool animation when you drag the FAB is gone?

**Comment by amanzan** [comment]
Just an FYI, I went back in the commit history and commit 5a708c8056fa8b372926b9f994f7b84bd4b3f068 is the one that somehow breaks the Follow-Circle animation

**Comment by lusccc** [comment]
Fixed~ Thanks~
