### ISSUE TITLE
In Last Collapsing animation of menu leaves traces of menu items on screen

### ISSUE THREAD

**Issue by vipulasri** [tiancaiCC/SpringFloatingActionMenu#2]
After collapsing the menu, animation leaves traces of menu items on main screen giving an unpleasant experience.

I know it is very minutely visible, but it is.

![Screenshot](https://s24.postimg.org/mv1gbnmjp/Untitled-1.png)

**Comment by lusccc** [comment]
I will solve it，thanks for your advice. 
😊

**Comment by lusccc** [comment]
Fixed. Sorry to let you wait so long.
