### ISSUE TITLE
Big Bug!

### ISSUE THREAD

**Issue by tellfa** [tiancaiCC/SpringFloatingActionMenu#4]
Hi man, I have a strange problem in this library!!!
I didn't open the menu, but click on application show me menu items title in toast!
please show below image : 
![quickmemo _2016-04-17-11-37-48](https://cloud.githubusercontent.com/assets/10583945/14585647/2892db5a-0491-11e6-9d38-f7e4de4c18cd.png)

please fix this big bug ;) Thanks

**Comment by lusccc** [comment]
My bad, I will fix it soon.

**Comment by tellfa** [comment]
When you put new update ?

**Comment by adeeljavedch** [comment]
@tellfa for now there is a way to handle this problem

in your onClick listener 

check if menu is open then perform onclick task

> if(build.isMenuOpen())
>  {
> ....
> }

**Comment by pishguy** [comment]
@adeel-quantumcph your code as `if(build.isMenuOpen())` doesnt work on sample code, how to do that?

**Comment by adeeljavedch** [comment]
@tux-world like this

```
  springFloatingActionMenu.addMenuItem(R.color.green,drawableId,"label", R.color.white,50, new View.OnClickListener() {
                         @Override
                         public void onClick(View v) {


                      if(build.isMenuOpen()) {

                              build.hideMenu();

                               //do something here

                          }

                      }
                   });


```

**Comment by pishguy** [comment]
@adeel-quantumcph Thanks, could you help me, how can i disable moving menu on screen?

**Comment by tellfa** [comment]
@adeel-quantumcph thanks man :heart:

**Comment by lusccc** [comment]
Fixed by @brucetoo. Thanks~
